
services:
  app:
    build: .
    command: pnpm start
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://stolyo:stolyo@db:5432/stolyo
      - NEXTAUTH_SECRET=changeme
      - EMAIL_SERVER_HOST=mail
      - EMAIL_SERVER_PORT=1025
      - EMAIL_SERVER_USER=user
      - EMAIL_SERVER_PASSWORD=pass
      - EMAIL_FROM=dev@stolyo.local
      - DASHBOARD_HOST=stolyo.local
    depends_on:
      - db
    volumes: []

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=stolyo
      - POSTGRES_PASSWORD=stolyo
      - POSTGRES_DB=stolyo
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app-dev:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "corepack enable && pnpm install && pnpm dev"
    ports:
      - "3000:3000"
    environment:
      - CI=true
      - PNPM_HOME=/pnpm
      - PNPM_DISABLE_SELF_UPDATE_CHECK=1
      - DATABASE_URL=postgresql://stolyo:stolyo@db:5432/stolyo
      - NEXTAUTH_SECRET=changeme
      - EMAIL_SERVER_HOST=mail
      - EMAIL_SERVER_PORT=1025
      - EMAIL_SERVER_USER=user
      - EMAIL_SERVER_PASSWORD=pass
      - EMAIL_FROM=dev@stolyo.local
      - DASHBOARD_HOST=stolyo.local
    volumes:
      - .:/app
      - app-dev-node-modules:/app/node_modules
    depends_on:
      - db

volumes:
  pgdata: {}
  app-dev-node-modules: {}